#!/bin/bash
pw-loopback --capture-props='media.class=Audio/Sink' --playback-props='audio.position=[FL FR]' -n cliradio-sink &
 
pw-loopback --capture-props='stream.capture.sink=true' -C cliradio-sink -m '[FL FR]' --playback-props='media.class=Audio/Source audio.position=[FL FR]' -n cliradio-internal-source &

